# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\manipulator.ui'
#
# Created: Mon Jul 13 15:26:04 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(540, 983)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridFrame = QtGui.QFrame(self.centralwidget)
        self.gridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gridFrame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 196, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.SM5Dev1PowerBtn = QtGui.QPushButton(self.gridFrame)
        self.SM5Dev1PowerBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.SM5Dev1PowerBtn.setCheckable(True)
        self.SM5Dev1PowerBtn.setObjectName(_fromUtf8("SM5Dev1PowerBtn"))
        self.gridLayout.addWidget(self.SM5Dev1PowerBtn, 6, 1, 1, 1)
        self.connectBtn = QtGui.QPushButton(self.gridFrame)
        self.connectBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.connectBtn.setCheckable(True)
        self.connectBtn.setDefault(False)
        self.connectBtn.setFlat(False)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.gridLayout.addWidget(self.connectBtn, 3, 0, 1, 2)
        self.SM5Dev2PowerBtn = QtGui.QPushButton(self.gridFrame)
        self.SM5Dev2PowerBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.SM5Dev2PowerBtn.setCheckable(True)
        self.SM5Dev2PowerBtn.setObjectName(_fromUtf8("SM5Dev2PowerBtn"))
        self.gridLayout.addWidget(self.SM5Dev2PowerBtn, 7, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.C843XYPowerBtn = QtGui.QPushButton(self.gridFrame)
        self.C843XYPowerBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.C843XYPowerBtn.setCheckable(True)
        self.C843XYPowerBtn.setChecked(False)
        self.C843XYPowerBtn.setObjectName(_fromUtf8("C843XYPowerBtn"))
        self.gridLayout.addWidget(self.C843XYPowerBtn, 6, 0, 1, 1)
        self.horizontalWidget = QtGui.QWidget(self.gridFrame)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget.setObjectName(_fromUtf8("horizontalWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.refLocationBtn = QtGui.QPushButton(self.horizontalWidget)
        self.refLocationBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.refLocationBtn.setObjectName(_fromUtf8("refLocationBtn"))
        self.horizontalLayout_2.addWidget(self.refLocationBtn)
        self.refNegativeBtn = QtGui.QPushButton(self.horizontalWidget)
        self.refNegativeBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.refNegativeBtn.setObjectName(_fromUtf8("refNegativeBtn"))
        self.horizontalLayout_2.addWidget(self.refNegativeBtn)
        self.gridLayout.addWidget(self.horizontalWidget, 9, 0, 1, 2)
        self.C843ZPowerBtn = QtGui.QPushButton(self.gridFrame)
        self.C843ZPowerBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.C843ZPowerBtn.setCheckable(True)
        self.C843ZPowerBtn.setObjectName(_fromUtf8("C843ZPowerBtn"))
        self.gridLayout.addWidget(self.C843ZPowerBtn, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gridFrame, 0, 0, 1, 2)
        self.gridFrame1 = QtGui.QFrame(self.centralwidget)
        self.gridFrame1.setMinimumSize(QtCore.QSize(0, 10))
        self.gridFrame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame1.setFrameShadow(QtGui.QFrame.Plain)
        self.gridFrame1.setLineWidth(2)
        self.gridFrame1.setObjectName(_fromUtf8("gridFrame1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridFrame1)
        self.gridLayout_8.setContentsMargins(9, 6, 6, 6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_13 = QtGui.QLabel(self.gridFrame1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 4, 0, 1, 1)
        self.horizontalWidget1 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget1.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget1.setObjectName(_fromUtf8("horizontalWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_4.setMargin(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.xIsPosDev1LE = QtGui.QLabel(self.horizontalWidget1)
        self.xIsPosDev1LE.setObjectName(_fromUtf8("xIsPosDev1LE"))
        self.horizontalLayout_4.addWidget(self.xIsPosDev1LE)
        self.yIsPosDev1LE = QtGui.QLabel(self.horizontalWidget1)
        self.yIsPosDev1LE.setObjectName(_fromUtf8("yIsPosDev1LE"))
        self.horizontalLayout_4.addWidget(self.yIsPosDev1LE)
        self.zIsPosDev1LE = QtGui.QLabel(self.horizontalWidget1)
        self.zIsPosDev1LE.setObjectName(_fromUtf8("zIsPosDev1LE"))
        self.horizontalLayout_4.addWidget(self.zIsPosDev1LE)
        self.gridLayout_8.addWidget(self.horizontalWidget1, 8, 1, 1, 1)
        self.horizontalWidget2 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget2.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget2.setObjectName(_fromUtf8("horizontalWidget2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalWidget2)
        self.horizontalLayout_13.setMargin(1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_24 = QtGui.QLabel(self.horizontalWidget2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_13.addWidget(self.label_24)
        self.device1StepLE = QtGui.QLineEdit(self.horizontalWidget2)
        self.device1StepLE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.device1StepLE.setObjectName(_fromUtf8("device1StepLE"))
        self.horizontalLayout_13.addWidget(self.device1StepLE)
        self.label_6 = QtGui.QLabel(self.horizontalWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.lineEdit_10 = QtGui.QLineEdit(self.horizontalWidget2)
        self.lineEdit_10.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_13.addWidget(self.lineEdit_10)
        self.gridLayout_8.addWidget(self.horizontalWidget2, 13, 0, 1, 2)
        self.label_23 = QtGui.QLabel(self.gridFrame1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 10, 0, 1, 1)
        self.horizontalWidget3 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget3.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget3.setObjectName(_fromUtf8("horizontalWidget3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalWidget3)
        self.horizontalLayout_12.setMargin(1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.xSetPosDev1LE = QtGui.QLineEdit(self.horizontalWidget3)
        self.xSetPosDev1LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.xSetPosDev1LE.setObjectName(_fromUtf8("xSetPosDev1LE"))
        self.horizontalLayout_12.addWidget(self.xSetPosDev1LE)
        self.ySetPosDev1LE = QtGui.QLineEdit(self.horizontalWidget3)
        self.ySetPosDev1LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ySetPosDev1LE.setObjectName(_fromUtf8("ySetPosDev1LE"))
        self.horizontalLayout_12.addWidget(self.ySetPosDev1LE)
        self.zSetPosDev1LE = QtGui.QLineEdit(self.horizontalWidget3)
        self.zSetPosDev1LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.zSetPosDev1LE.setObjectName(_fromUtf8("zSetPosDev1LE"))
        self.horizontalLayout_12.addWidget(self.zSetPosDev1LE)
        self.gridLayout_8.addWidget(self.horizontalWidget3, 10, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridFrame1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridFrame1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridFrame1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 8, 0, 1, 1)
        self.horizontalWidget4 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget4.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget4.setObjectName(_fromUtf8("horizontalWidget4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalWidget4)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.xIsPosDev2LE = QtGui.QLabel(self.horizontalWidget4)
        self.xIsPosDev2LE.setObjectName(_fromUtf8("xIsPosDev2LE"))
        self.horizontalLayout_3.addWidget(self.xIsPosDev2LE)
        self.yIsPosDev2LE = QtGui.QLabel(self.horizontalWidget4)
        self.yIsPosDev2LE.setObjectName(_fromUtf8("yIsPosDev2LE"))
        self.horizontalLayout_3.addWidget(self.yIsPosDev2LE)
        self.zIsPosDev2LE = QtGui.QLabel(self.horizontalWidget4)
        self.zIsPosDev2LE.setObjectName(_fromUtf8("zIsPosDev2LE"))
        self.horizontalLayout_3.addWidget(self.zIsPosDev2LE)
        self.gridLayout_8.addWidget(self.horizontalWidget4, 8, 2, 1, 1)
        self.horizontalWidget5 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget5.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget5.setObjectName(_fromUtf8("horizontalWidget5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalWidget5)
        self.horizontalLayout_11.setMargin(2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_18 = QtGui.QLabel(self.horizontalWidget5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_11.addWidget(self.label_18)
        self.stepLineEdit = QtGui.QLineEdit(self.horizontalWidget5)
        self.stepLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.stepLineEdit.setObjectName(_fromUtf8("stepLineEdit"))
        self.horizontalLayout_11.addWidget(self.stepLineEdit)
        self.label_19 = QtGui.QLabel(self.horizontalWidget5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_11.addWidget(self.label_19)
        self.speedLineEdit = QtGui.QLineEdit(self.horizontalWidget5)
        self.speedLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.speedLineEdit.setObjectName(_fromUtf8("speedLineEdit"))
        self.horizontalLayout_11.addWidget(self.speedLineEdit)
        self.gridLayout_8.addWidget(self.horizontalWidget5, 6, 0, 1, 3)
        self.horizontalWidget6 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget6.setObjectName(_fromUtf8("horizontalWidget6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget6)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fineBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.fineBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fineBtn.setIconSize(QtCore.QSize(16, 16))
        self.fineBtn.setCheckable(True)
        self.fineBtn.setObjectName(_fromUtf8("fineBtn"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.fineBtn)
        self.horizontalLayout.addWidget(self.fineBtn)
        self.smallBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.smallBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.smallBtn.setCheckable(True)
        self.smallBtn.setObjectName(_fromUtf8("smallBtn"))
        self.buttonGroup.addButton(self.smallBtn)
        self.horizontalLayout.addWidget(self.smallBtn)
        self.mediumBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.mediumBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.mediumBtn.setCheckable(True)
        self.mediumBtn.setObjectName(_fromUtf8("mediumBtn"))
        self.buttonGroup.addButton(self.mediumBtn)
        self.horizontalLayout.addWidget(self.mediumBtn)
        self.coarseBtn = QtGui.QPushButton(self.horizontalWidget6)
        self.coarseBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.coarseBtn.setCheckable(True)
        self.coarseBtn.setObjectName(_fromUtf8("coarseBtn"))
        self.buttonGroup.addButton(self.coarseBtn)
        self.horizontalLayout.addWidget(self.coarseBtn)
        self.gridLayout_8.addWidget(self.horizontalWidget6, 5, 0, 1, 3)
        self.horizontalWidget7 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget7.setObjectName(_fromUtf8("horizontalWidget7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalWidget7)
        self.horizontalLayout_8.setMargin(1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.setXLocationLineEdit = QtGui.QLineEdit(self.horizontalWidget7)
        self.setXLocationLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.setXLocationLineEdit.setText(_fromUtf8(""))
        self.setXLocationLineEdit.setObjectName(_fromUtf8("setXLocationLineEdit"))
        self.horizontalLayout_8.addWidget(self.setXLocationLineEdit)
        self.setYLocationLineEdit = QtGui.QLineEdit(self.horizontalWidget7)
        self.setYLocationLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.setYLocationLineEdit.setText(_fromUtf8(""))
        self.setYLocationLineEdit.setObjectName(_fromUtf8("setYLocationLineEdit"))
        self.horizontalLayout_8.addWidget(self.setYLocationLineEdit)
        self.setZLocationLineEdit = QtGui.QLineEdit(self.horizontalWidget7)
        self.setZLocationLineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.setZLocationLineEdit.setText(_fromUtf8(""))
        self.setZLocationLineEdit.setObjectName(_fromUtf8("setZLocationLineEdit"))
        self.horizontalLayout_8.addWidget(self.setZLocationLineEdit)
        self.gridLayout_8.addWidget(self.horizontalWidget7, 4, 1, 1, 2)
        self.horizontalWidget8 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget8.setObjectName(_fromUtf8("horizontalWidget8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalWidget8)
        self.horizontalLayout_9.setMargin(4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.isXLocationValueLabel = QtGui.QLabel(self.horizontalWidget8)
        self.isXLocationValueLabel.setObjectName(_fromUtf8("isXLocationValueLabel"))
        self.horizontalLayout_9.addWidget(self.isXLocationValueLabel)
        self.isYLocationValueLabel = QtGui.QLabel(self.horizontalWidget8)
        self.isYLocationValueLabel.setObjectName(_fromUtf8("isYLocationValueLabel"))
        self.horizontalLayout_9.addWidget(self.isYLocationValueLabel)
        self.isZLocationValueLabel = QtGui.QLabel(self.horizontalWidget8)
        self.isZLocationValueLabel.setObjectName(_fromUtf8("isZLocationValueLabel"))
        self.horizontalLayout_9.addWidget(self.isZLocationValueLabel)
        self.gridLayout_8.addWidget(self.horizontalWidget8, 3, 1, 1, 2)
        self.horizontalWidget9 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget9.setObjectName(_fromUtf8("horizontalWidget9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalWidget9)
        self.horizontalLayout_7.setMargin(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.minMaxXLocationValueLabel = QtGui.QLabel(self.horizontalWidget9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.minMaxXLocationValueLabel.setFont(font)
        self.minMaxXLocationValueLabel.setObjectName(_fromUtf8("minMaxXLocationValueLabel"))
        self.horizontalLayout_7.addWidget(self.minMaxXLocationValueLabel)
        self.minMaxYLocationValueLabel = QtGui.QLabel(self.horizontalWidget9)
        self.minMaxYLocationValueLabel.setObjectName(_fromUtf8("minMaxYLocationValueLabel"))
        self.horizontalLayout_7.addWidget(self.minMaxYLocationValueLabel)
        self.minMaxZLocationValueLabel = QtGui.QLabel(self.horizontalWidget9)
        self.minMaxZLocationValueLabel.setObjectName(_fromUtf8("minMaxZLocationValueLabel"))
        self.horizontalLayout_7.addWidget(self.minMaxZLocationValueLabel)
        self.gridLayout_8.addWidget(self.horizontalWidget9, 2, 1, 1, 2)
        self.controllerActivateBtn = QtGui.QPushButton(self.gridFrame1)
        self.controllerActivateBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.controllerActivateBtn.setStyleSheet(_fromUtf8(""))
        self.controllerActivateBtn.setCheckable(True)
        self.controllerActivateBtn.setChecked(False)
        self.controllerActivateBtn.setObjectName(_fromUtf8("controllerActivateBtn"))
        self.gridLayout_8.addWidget(self.controllerActivateBtn, 1, 0, 1, 3)
        self.label_8 = QtGui.QLabel(self.gridFrame1)
        self.label_8.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgb(0, 196, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 3)
        self.horizontalWidget10 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget10.setObjectName(_fromUtf8("horizontalWidget10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalWidget10)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.xSetPosDev2LE = QtGui.QLineEdit(self.horizontalWidget10)
        self.xSetPosDev2LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.xSetPosDev2LE.setObjectName(_fromUtf8("xSetPosDev2LE"))
        self.horizontalLayout_5.addWidget(self.xSetPosDev2LE)
        self.ySetPosDev2LE = QtGui.QLineEdit(self.horizontalWidget10)
        self.ySetPosDev2LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ySetPosDev2LE.setObjectName(_fromUtf8("ySetPosDev2LE"))
        self.horizontalLayout_5.addWidget(self.ySetPosDev2LE)
        self.zSetPosDev2LE = QtGui.QLineEdit(self.horizontalWidget10)
        self.zSetPosDev2LE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.zSetPosDev2LE.setObjectName(_fromUtf8("zSetPosDev2LE"))
        self.horizontalLayout_5.addWidget(self.zSetPosDev2LE)
        self.gridLayout_8.addWidget(self.horizontalWidget10, 10, 2, 1, 1)
        self.horizontalWidget11 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget11.setObjectName(_fromUtf8("horizontalWidget11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalWidget11)
        self.horizontalLayout_10.setMargin(1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.device2StepLE = QtGui.QLineEdit(self.horizontalWidget11)
        self.device2StepLE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.device2StepLE.setObjectName(_fromUtf8("device2StepLE"))
        self.horizontalLayout_10.addWidget(self.device2StepLE)
        self.label_12 = QtGui.QLabel(self.horizontalWidget11)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.lineEdit = QtGui.QLineEdit(self.horizontalWidget11)
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.gridLayout_8.addWidget(self.horizontalWidget11, 13, 2, 1, 1)
        self.horizontalWidget12 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget12.setObjectName(_fromUtf8("horizontalWidget12"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.horizontalWidget12)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.trackStageZMovementDev2Btn = QtGui.QPushButton(self.horizontalWidget12)
        self.trackStageZMovementDev2Btn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.trackStageZMovementDev2Btn.setObjectName(_fromUtf8("trackStageZMovementDev2Btn"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.trackStageZMovementDev2Btn)
        self.horizontalLayout_14.addWidget(self.trackStageZMovementDev2Btn)
        self.trackStageXMovementDev2Btn = QtGui.QPushButton(self.horizontalWidget12)
        self.trackStageXMovementDev2Btn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.trackStageXMovementDev2Btn.setObjectName(_fromUtf8("trackStageXMovementDev2Btn"))
        self.buttonGroup_3.addButton(self.trackStageXMovementDev2Btn)
        self.horizontalLayout_14.addWidget(self.trackStageXMovementDev2Btn)
        self.gridLayout_8.addWidget(self.horizontalWidget12, 14, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridFrame1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 14, 0, 1, 1)
        self.horizontalWidget13 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget13.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget13.setObjectName(_fromUtf8("horizontalWidget13"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalWidget13)
        self.horizontalLayout_6.setMargin(1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.trackStageZMovementDev1Btn = QtGui.QPushButton(self.horizontalWidget13)
        self.trackStageZMovementDev1Btn.setMinimumSize(QtCore.QSize(0, 0))
        self.trackStageZMovementDev1Btn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.trackStageZMovementDev1Btn.setIconSize(QtCore.QSize(16, 16))
        self.trackStageZMovementDev1Btn.setCheckable(True)
        self.trackStageZMovementDev1Btn.setObjectName(_fromUtf8("trackStageZMovementDev1Btn"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.trackStageZMovementDev1Btn)
        self.horizontalLayout_6.addWidget(self.trackStageZMovementDev1Btn)
        self.trackStageXMovementDev1Btn = QtGui.QPushButton(self.horizontalWidget13)
        self.trackStageXMovementDev1Btn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.trackStageXMovementDev1Btn.setCheckable(True)
        self.trackStageXMovementDev1Btn.setObjectName(_fromUtf8("trackStageXMovementDev1Btn"))
        self.buttonGroup_2.addButton(self.trackStageXMovementDev1Btn)
        self.horizontalLayout_6.addWidget(self.trackStageXMovementDev1Btn)
        self.gridLayout_8.addWidget(self.horizontalWidget13, 14, 1, 1, 1)
        self.horizontalWidget14 = QtGui.QWidget(self.gridFrame1)
        self.horizontalWidget14.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget14.setObjectName(_fromUtf8("horizontalWidget14"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.horizontalWidget14)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.activateDev1 = QtGui.QPushButton(self.horizontalWidget14)
        self.activateDev1.setMaximumSize(QtCore.QSize(16777215, 24))
        self.activateDev1.setSizeIncrement(QtCore.QSize(0, 0))
        self.activateDev1.setCheckable(True)
        self.activateDev1.setObjectName(_fromUtf8("activateDev1"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.activateDev1)
        self.horizontalLayout_15.addWidget(self.activateDev1)
        self.activateDev2 = QtGui.QPushButton(self.horizontalWidget14)
        self.activateDev2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.activateDev2.setCheckable(True)
        self.activateDev2.setObjectName(_fromUtf8("activateDev2"))
        self.buttonGroup_4.addButton(self.activateDev2)
        self.horizontalLayout_15.addWidget(self.activateDev2)
        self.gridLayout_8.addWidget(self.horizontalWidget14, 7, 1, 1, 2)
        self.gridLayout_3.addWidget(self.gridFrame1, 1, 0, 1, 2)
        self.gridFrame2 = QtGui.QFrame(self.centralwidget)
        self.gridFrame2.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gridFrame2.setObjectName(_fromUtf8("gridFrame2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridFrame2)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.removeItemBtn = QtGui.QPushButton(self.gridFrame2)
        self.removeItemBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.removeItemBtn.setObjectName(_fromUtf8("removeItemBtn"))
        self.gridLayout_2.addWidget(self.removeItemBtn, 6, 1, 1, 1)
        self.recordDepthBtn = QtGui.QPushButton(self.gridFrame2)
        self.recordDepthBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.recordDepthBtn.setObjectName(_fromUtf8("recordDepthBtn"))
        self.gridLayout_2.addWidget(self.recordDepthBtn, 6, 0, 1, 1)
        self.moveToItemBtn = QtGui.QPushButton(self.gridFrame2)
        self.moveToItemBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.moveToItemBtn.setObjectName(_fromUtf8("moveToItemBtn"))
        self.gridLayout_2.addWidget(self.moveToItemBtn, 5, 0, 1, 1)
        self.updateItemLocationBtn = QtGui.QPushButton(self.gridFrame2)
        self.updateItemLocationBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.updateItemLocationBtn.setObjectName(_fromUtf8("updateItemLocationBtn"))
        self.gridLayout_2.addWidget(self.updateItemLocationBtn, 5, 1, 1, 1)
        self.electrode2MLIBtn = QtGui.QPushButton(self.gridFrame2)
        self.electrode2MLIBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.electrode2MLIBtn.setObjectName(_fromUtf8("electrode2MLIBtn"))
        self.gridLayout_2.addWidget(self.electrode2MLIBtn, 1, 1, 1, 1)
        self.electrode1MLIBtn = QtGui.QPushButton(self.gridFrame2)
        self.electrode1MLIBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.electrode1MLIBtn.setObjectName(_fromUtf8("electrode1MLIBtn"))
        self.gridLayout_2.addWidget(self.electrode1MLIBtn, 1, 0, 1, 1)
        self.electrode1PCBtn = QtGui.QPushButton(self.gridFrame2)
        self.electrode1PCBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.electrode1PCBtn.setObjectName(_fromUtf8("electrode1PCBtn"))
        self.gridLayout_2.addWidget(self.electrode1PCBtn, 2, 0, 1, 1)
        self.electrode2PCBtn = QtGui.QPushButton(self.gridFrame2)
        self.electrode2PCBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.electrode2PCBtn.setObjectName(_fromUtf8("electrode2PCBtn"))
        self.gridLayout_2.addWidget(self.electrode2PCBtn, 2, 1, 1, 1)
        self.cellListTable = QtGui.QTableWidget(self.gridFrame2)
        self.cellListTable.setMaximumSize(QtCore.QSize(16777215, 115))
        self.cellListTable.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cellListTable.setRowCount(4)
        self.cellListTable.setObjectName(_fromUtf8("cellListTable"))
        self.cellListTable.setColumnCount(5)
        item = QtGui.QTableWidgetItem()
        self.cellListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cellListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cellListTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.cellListTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.cellListTable.setHorizontalHeaderItem(4, item)
        self.cellListTable.horizontalHeader().setStretchLastSection(True)
        self.cellListTable.verticalHeader().setVisible(False)
        self.cellListTable.verticalHeader().setDefaultSectionSize(22)
        self.gridLayout_2.addWidget(self.cellListTable, 4, 0, 1, 2)
        self.label_25 = QtGui.QLabel(self.gridFrame2)
        self.label_25.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("background-color: rgb(0, 196, 255);\n"
""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 2)
        self.saveLocationsBtn = QtGui.QPushButton(self.gridFrame2)
        self.saveLocationsBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.saveLocationsBtn.setObjectName(_fromUtf8("saveLocationsBtn"))
        self.gridLayout_2.addWidget(self.saveLocationsBtn, 7, 0, 1, 1)
        self.loadLocationsBtn = QtGui.QPushButton(self.gridFrame2)
        self.loadLocationsBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.loadLocationsBtn.setObjectName(_fromUtf8("loadLocationsBtn"))
        self.gridLayout_2.addWidget(self.loadLocationsBtn, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gridFrame2, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Connection Panel", None))
        self.SM5Dev1PowerBtn.setText(_translate("MainWindow", "Switch Off XYZ of Manip1", None))
        self.connectBtn.setText(_translate("MainWindow", "Connect SM-5 and C-843", None))
        self.SM5Dev2PowerBtn.setText(_translate("MainWindow", "Switch Off XYZ of Manip2", None))
        self.label_3.setText(_translate("MainWindow", "Luigs&Neumann SM-5", None))
        self.label_4.setText(_translate("MainWindow", "Physik Instrumente C-843", None))
        self.label_7.setText(_translate("MainWindow", "C-843 Reference ", None))
        self.C843XYPowerBtn.setText(_translate("MainWindow", "Switch Off XY", None))
        self.refLocationBtn.setText(_translate("MainWindow", "Saved Stage Location", None))
        self.refNegativeBtn.setText(_translate("MainWindow", "Negative Switch Limit", None))
        self.C843ZPowerBtn.setText(_translate("MainWindow", "Switch Off Z", None))
        self.label_13.setText(_translate("MainWindow", "set pos. (μm)", None))
        self.xIsPosDev1LE.setText(_translate("MainWindow", ".", None))
        self.yIsPosDev1LE.setText(_translate("MainWindow", ".", None))
        self.zIsPosDev1LE.setText(_translate("MainWindow", ".", None))
        self.label_24.setText(_translate("MainWindow", "Step (μm) : Speed", None))
        self.label_6.setText(_translate("MainWindow", ":", None))
        self.label_23.setText(_translate("MainWindow", "set pos. (μm)", None))
        self.label_9.setText(_translate("MainWindow", "max pos. (μm)", None))
        self.label_17.setText(_translate("MainWindow", "cur. pos. (μm)", None))
        self.label.setText(_translate("MainWindow", "cur. pos. (μm)", None))
        self.xIsPosDev2LE.setText(_translate("MainWindow", ".", None))
        self.yIsPosDev2LE.setText(_translate("MainWindow", ".", None))
        self.zIsPosDev2LE.setText(_translate("MainWindow", ".", None))
        self.label_18.setText(_translate("MainWindow", "Step (μm) : Speed", None))
        self.label_19.setText(_translate("MainWindow", ":", None))
        self.fineBtn.setText(_translate("MainWindow", "Fine", None))
        self.smallBtn.setText(_translate("MainWindow", "Small", None))
        self.mediumBtn.setText(_translate("MainWindow", "Medium", None))
        self.coarseBtn.setText(_translate("MainWindow", "Coarse", None))
        self.isXLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.isYLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.isZLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.minMaxXLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.minMaxYLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.minMaxZLocationValueLabel.setText(_translate("MainWindow", ".", None))
        self.controllerActivateBtn.setText(_translate("MainWindow", "Activate Controller", None))
        self.label_8.setText(_translate("MainWindow", "Move Panel", None))
        self.label_12.setText(_translate("MainWindow", ":", None))
        self.trackStageZMovementDev2Btn.setText(_translate("MainWindow", "z-Movement", None))
        self.trackStageXMovementDev2Btn.setText(_translate("MainWindow", "x-Movement", None))
        self.label_5.setText(_translate("MainWindow", "Track Stage", None))
        self.trackStageZMovementDev1Btn.setText(_translate("MainWindow", "z-Movement", None))
        self.trackStageXMovementDev1Btn.setText(_translate("MainWindow", "x-Movement", None))
        self.activateDev1.setText(_translate("MainWindow", "Manipulator 1", None))
        self.activateDev2.setText(_translate("MainWindow", "Manipulator 2", None))
        self.removeItemBtn.setText(_translate("MainWindow", "Remove Item", None))
        self.recordDepthBtn.setText(_translate("MainWindow", "Record Depth", None))
        self.moveToItemBtn.setText(_translate("MainWindow", "Move to Item", None))
        self.updateItemLocationBtn.setText(_translate("MainWindow", "Update Item Location", None))
        self.electrode2MLIBtn.setText(_translate("MainWindow", "E2 MLI", None))
        self.electrode1MLIBtn.setText(_translate("MainWindow", "E1 MLI", None))
        self.electrode1PCBtn.setText(_translate("MainWindow", "E1 PC", None))
        self.electrode2PCBtn.setText(_translate("MainWindow", "E2 PC", None))
        item = self.cellListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#", None))
        item = self.cellListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "type", None))
        item = self.cellListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.cellListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "depth", None))
        item = self.cellListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "location", None))
        self.label_25.setText(_translate("MainWindow", "List of recorded Locations", None))
        self.saveLocationsBtn.setText(_translate("MainWindow", "Save Locations", None))
        self.loadLocationsBtn.setText(_translate("MainWindow", "Load Locations", None))

